version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  shellcheck: circleci/shellcheck@2.0.0

jobs:
  sanity-check:
    # This MUST be a machine
    # because it needs access to docker volume mounting
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: setup
          command: sbin/setup.sh
      - run:
          name: overview
          command: sbin/overview.sh
      - run:
          name: tuts_simple
          command: sbin/tuts_simple.sh
      - run:
          name: tut_7
          command: sbin/tut_7.sh
      - run:
          name: workshops_simple
          command: sbin/workshops_simple.sh
      - slack/status:
          fail_only: true

workflows:
  on-push:
    jobs:
      - sanity-check
  lint:
    jobs:
      - shellcheck/check
  nightly:
    triggers:
    - schedule:
        cron: "0 10 * * *" # 6am EST
        filters:
          branches:
            only:
              - master
    jobs:
      - sanity-check
