version: 2.1
orbs:
  slack: circleci/slack@4.1.1
  shellcheck: circleci/shellcheck@2.2.0
  docker: circleci/docker@1.5.0

x-slack-notify-on-fail: &slack-notify-on-fail
  slack/notify:
    event: fail
    template: basic_fail_1

jobs:
  sanity-check:
    # This MUST be a machine
    # because it needs access to docker volume mounting
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - docker/check # logs in w/ $DOCKER_LOGIN & $DOCKER_PASSWORD
      - run:
          name: docker id
          command: docker info --format '{{.ID}}' 2>/dev/null
      - run:
          name: setup
          command: sbin/setup.sh
      - run:
          name: hashes
          command: sbin/hashes.sh
      - run:
          name: overview
          command: sbin/overview.sh
      - run:
          name: tuts_simple
          command: sbin/tuts_simple.sh
      - run:
          name: tut_8
          command: sbin/tut_8.sh
      - run:
          name: workshops_simple
          command: sbin/workshops_simple.sh
      - run:
          name: test_init
          command: sbin/test_init.sh
      - run:
          name: check hs image is up to date
          command: sbin/hs.sh
      - run:
          name: check js images are up to date
          command: sbin/js.sh
      - run:
          name: check algorand-devnet is up to date
          command: sbin/algorand_devnet.sh
      - run:
          name: check ethereum-devnet is up to date
          command: sbin/ethereum_devnet.sh
      - <<: *slack-notify-on-fail

x-default-job-setup: &default-job-setup
  context:
    - reachdevbot-on-dockerhub
    - circleci-on-slack

workflows:
  on-push:
    jobs:
      - sanity-check:
          <<: *default-job-setup
  lint:
    jobs:
      - shellcheck/check

  nightly:
    triggers:
    - schedule:
        cron: "0 10 * * *" # 6am EDT
        filters:
          branches:
            only:
              - master
    jobs:
      - sanity-check:
          <<: *default-job-setup
